name = "lienlibre"
main = "worker.js"
compatibility_date = "2024-05-25"

# Configuration du stockage Cloudflare KV pour les statistiques en temps réel
[[kv_namespaces]]
binding = "LIENLIBRE_KV"
id = "24b98863e85944ed996cbde9dcdb8c13"
